tank_api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.helper, name='api-helper'),
    path('events/', views.events, name='get-events'),
    path('average/', views.average, name='get-average'),
    path('sum_price/', views.sum_price, name='sum-price')
]

tank_logic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.history, name='history-view'),
    path('new/', views.new_tank, name='new-tank-view'),
    path('stat/', views.stat, name="stat-view"),
    path('service/', views.service, name="service-view"),
    path('save_service/', views.save_service, name="save_service"),
    path('delete_event/<str:eventtype>/<int:id>', views.delete_event, name="delete_event"),
]

tank_you/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tankapi/', include('tank_api.urls')),
    path('tank/', include('tank_logic.urls'))
]

tank_logic/models.py
from django.db import models
from datetime import date
from django.db import models
from datetime import date

PETROL_CHOICES = (
    ('gasoline95', '95-ös benzin'),
    ('gasoline100', '100-as benzin'),
    ('diesel', 'dízel'),
)

PETROL_STATION_CHOICES = (
    ('mol', 'MOL'),
    ('shell', 'Shell'),
    ('omv', 'OMV')
)

class TankEvent(models.Model):
    km = models.IntegerField(default=0)
    petrol_type = models.CharField(max_length=20, choices=PETROL_CHOICES, default='gasoline95')
    petrol_station = models.CharField(max_length=20, choices=PETROL_STATION_CHOICES, default='mol')
    petrol_quantity_liter = models.FloatField(default=0.0)
    price_ft = models.FloatField(default=0.0)
    date = models.DateTimeField(auto_now_add=True, blank=True)

    def to_class_name(value):
        return value.__class__.__name__

    def __str__(self):
        return (f'{self.km} - {self.date}')

class ServiceEvent(models.Model):
    km = models.IntegerField(default=0)
    note = models.TextField()
    date = models.DateTimeField(auto_now_add=True, blank=True)
    price_ft = models.FloatField(default=0.0)
    
    def to_class_name(value):
        return value.__class__.__name__

    def __str__(self):
        return (f'{self.km} - {self.date}')

tank_api/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from tank_logic.models import TankEvent
from .serializers import TankEventSerializer
from tank_logic import calculations

@api_view(['GET'])
def helper(request):
    api_urls = {
        'tankapi/':'API map',
        'tankapi/events/':'Return the tank events',
        'tankapi/average/':'Return the average fuel use in 100 km',
        'tankapi/sum_price/':'Return the summed price in HUF'
    }
    return Response(api_urls)

@api_view(['GET'])
def events(request):
    events = TankEvent.objects.all()
    serializer = TankEventSerializer(events, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def average(request):
    events = TankEvent.objects.all().order_by('-date')
    average = {
        'average_consumption': calculations.calculate_consumption(events),
        'fuel_unit':'liter',
        'distance': 100,
        'distance_unit': 'kilometer'
    }
    return Response(average)

@api_view(['GET'])
def sum_price(request):
    sprice = {
        'summed_price': calculations.sum_price(TankEvent.objects.all()),
        'currency': 'HUF'
    }
    return Response(sprice)

tank_logic/views.py
from django.shortcuts import render, redirect
from .models import TankEvent, ServiceEvent, PETROL_CHOICES, PETROL_STATION_CHOICES
from . import calculations

def new_tank(request):
    if request.method=='POST':
        km = request.POST['km']
        petrol_type = request.POST['petrol_type']
        petrol_station = request.POST['petrol_station']
        petrol_quantity_liter = request.POST['petrol_quantity_liter']
        price_ft = request.POST['price_ft']
        new_event = TankEvent(
            km = km,
            petrol_type = petrol_type,
            petrol_station = petrol_station,
            petrol_quantity_liter = petrol_quantity_liter,
            price_ft = price_ft
        )
        new_event.save()
        return redirect('history-view')
    context =  {
        'petrol_types':PETROL_CHOICES,
        'petrol_stations':PETROL_STATION_CHOICES,
    }
    return render(request, 'tank/new_tank.html', context)

def history(request):
    
    events = list(TankEvent.objects.all().order_by('-date'))
    events += list(ServiceEvent.objects.all().order_by('-date'))

    events.sort(key=lambda x: x.date, reverse=True)

    context = {
        'events':events,
    }
    return render(request, 'tank/history.html', context)

def stat(request):
    tank_events = TankEvent.objects.all().order_by('-date')

    events = list(TankEvent.objects.all().order_by('-date'))
    events += list(ServiceEvent.objects.all().order_by('-date'))

    context = {
        'last': calculations.getElementFromEvents(tank_events, 0),
        'consumption': calculations.calculate_consumption(tank_events),
        'average_quantity':calculations.calculate_average_quantity(tank_events),
        'average_price': calculations.calculate_average_price(tank_events),
        'sum_price': calculations.sum_price(events),
    }

    return render(request, 'tank/stat.html', context)

def service(request):
    return render(request, 'tank/service.html')

def save_service(request):
    if(request.method == 'POST'):
        km = request.POST['km']
        note = request.POST['note']
        price_ft = request.POST['price_ft']

        new_sevice_event = ServiceEvent(
            km = km,
            note = note,
            price_ft = price_ft
        )
        new_sevice_event.save()
        return redirect('history-view')
    return redirect('service-view')

def delete_event(request, eventtype, id):
    if eventtype == 'TankEvent':
        removable_event = TankEvent.objects.filter(id=id)[0]
        removable_event.delete()
    elif eventtype == 'ServiceEvent':
        removable_event = ServiceEvent.objects.filter(id=id)[0]
        removable_event.delete()
    return redirect('history-view')

templates/tank/base.html
<!DOCTYPE html>
<html lang="hu">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TankYou</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  <style>
    body{
      min-height: 100vh;
      background-color: rgb(245, 245, 245);
      font-size: 20px;
      padding-bottom: 50px;
    }

    .menu{
      display: flex;
      justify-content: space-between;
    }

    .container{
      width: 80%;
      max-width: 500px;
      margin-top: 50px;
    }
    #menu_button{
      display: none;
      width: 70px;
      height: 70px;
      margin-left: calc(100% - 80px);
      margin-top: 10px;
      box-sizing: border-box;
      font-size: 3rem;
      border: none;
    }
    .menu a{
        display: block;
        text-align: center;
        height: 50px;
        background-color: rgb(221, 221, 221);
        color: black;
        font-weight: bold;
        line-height:50px;
        margin-bottom: 5px;
        text-decoration: none;
        transition: 1s;
        padding: 0px 10px;
      }

      .menu a:hover{
        background-color: rgb(172, 172, 172);
      }

      h1{
        text-align: center;
        margin-top: 30vh;
      }

    @media screen and (max-width: 700px) {
      .container{
        margin-top: 10px;
      }
      #menu_button{
        display: block;
      }
      .menu{
        display: block;
        height: 0px;
        overflow: hidden;
        transition: 0.2s;
      }

      .open_menu{
        height: 240px;
      }



    }
  </style>
  
  {% block head %}
  {% endblock %}
</head>
<body>
<button id="menu_button" onclick="open_menu()">&#9776</button>
<div class="container menu" id="menu">
  <a href="{% url 'history-view' %}">Események</a>
  <a href="{% url 'new-tank-view' %}">Tankolás</a>
  <a href="{% url 'service-view' %}">Szerviz</a>
  <a href="{% url 'stat-view' %}">Statisztika</a>
</div>

{% block main %}
{% endblock %}

<script>
  let menu = document.getElementById('menu');

  function open_menu(){
    if(menu.classList.contains('open_menu'))
      menu.classList.remove('open_menu')
    else
      menu.classList.add('open_menu');
  }
</script>
{% block script %}
{% endblock %}
</body>
</html>

templates/tank/history.html
{% extends "tank/base.html" %}

{% block head %}
<style>
    [class*="col-"] {
      padding: 10px 20px;
    }

    .event{
      background-color: white;
      width: 100%;
      box-sizing: border-box;
      padding: 10px;
      border-radius: 5px;
      box-shadow:0px 0px 10px rgba(0, 0, 0, 0.5);
      margin-bottom: 50px;
    }

    .date{
      font-weight: bold;
      font-size: 1.2rem;
    }
    .time{
      float: right;
      font-style: italic;
    }

    .label{
      font-weight: bold;
      text-align: right;
    }

    .delete a {
      color: rgba(255, 0, 0, 0.548);;
      text-decoration:none;
      padding: 15px;
      transition: 1s;
      float: right;
      display: block;
      width: 120px;
      text-align: center;
    }

    .delete a:hover {
      color: white;
      text-decoration:none;
      background-color: rgba(255, 0, 0, 0.6);
      padding: 15px;
    }

    .price{
      font-size: 1.5rem;
      font-style: italic;
      text-align: right;
      padding-right: 20px;
    }

    .service{
      background-color: rgba(255, 255, 0, 0.4);
    }

    .service-note{
      font-weight: bold;
      text-align: center;
      font-size: 1.5rem;
    }

    #previous-events .time span{
        padding: 0;
        margin: 0;
    }

    @media screen and (max-width: 576px) {
      .label, #previous-events span, .date, .time  {
        text-align: center;
        width: 100%;
        display: block;
        float: none;
      }

      #previous-events .time span{
        display: inline;
      }

      .date{
        font-size: 2rem;
      }

      [class*="col-"] {
        padding: 0px;
      }
      .row{
        margin-bottom: 15px;
      }   
    }

  </style>
{% endblock %}

{% block main %}
<div id="previous-events" class="container">
  {% if events.0 == None %}
  <h1>Még nincs egy eseményed sem!</h1>
  {% else %}
    {% for event in events %}
    {% if event.to_class_name == 'TankEvent' %}
    <div class="event">
      <div class="row">
        <div class="col-sm-6">
          <span class="date">{{ event.date|date:"Y.m.d." }}</span>
        </div>
        <div class="col-sm-6">
          <span class="time">
            {{ event.date|date:"H:i"}}
          </span>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 label">
          Km óra állása:
        </div>
        <div class="col-sm-6">
          <span class="mileage">{{ event.km }}km</span>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 label">Tankolt üzemanyag:</div>
        <div class="col-sm-6">
          <span>{{ event.petrol_quantity_liter }}l</span><br>
          <span>({{ event.petrol_type }}, {{ event.petrol_station }})</span>
  
        </div>
      </div>
      <div class="row">
        <span class="price">{{ event.price_ft}} Ft</span>
      </div>
      <div class="row delete">
        <div class="col">
          <a href="{% url 'delete_event' event.to_class_name event.id %}">Törlés</a>
        </div>
      </div>

    </div>
    {% else %}
      {% if event.to_class_name == 'ServiceEvent' %}
    <div class="event service">
      <div class="row">
        <div class="col-sm-6">
          <span class="date">{{ event.date|date:"Y.m.d." }}</span>
        </div>
        <div class="col-sm-6">
          <span class="time">
            {{ event.date|date:"H:i"}}
          </span>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 label">
          Km óra állása:
        </div>
        <div class="col-sm-6">
          <span class="mileage">{{ event.km }}km</span>
        </div>
      </div>
      <div class="row">
        <div class="col service-note">{{ event.note }}</div>
      </div>
      <div class="row">
        <span class="price">{{ event.price_ft}} Ft</span>
      </div>
      <div class="row delete">
        <div class="col">
          <a href="{% url 'delete_event' event.to_class_name event.id %}">Törlés</a>
        </div>
      </div>
    </div>
      {% endif %}
    {% endif %}
    {% endfor %}
  </div>
  {% endif %}
{% endblock %}

{% block script %}
{% endblock %}

templates/tank/new_tank.html
{% extends "tank/base.html" %}

{% block head %}
<style>

    .row{
      width: 100%;
    }

    input, select{
      width: 100%;
      height: 2.5rem;
    }

    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }

    input[type=submit]{
      height: 70px;
      max-width: 200px;
      float: right;
      border: none;
      background-color: rgba(0, 128, 0, 0.2);
      transition: 1s;
      font-weight: bold;
    }

    input[type=submit]:hover{
      background-color: rgba(0, 128, 0, 0.4);
    }

    input[type=number] {
      -moz-appearance: textfield;
    }

    [class*="col-"] {
      padding: 10px;
    }

    .event{
      background-color: white;
      width: 100%;
      box-sizing: border-box;
      padding: 10px;
      border-radius: 5px;
      box-shadow:0px 0px 10px rgba(0, 0, 0, 0.5);
      margin-bottom: 50px;
    }

    .date{
      font-weight: bold;
      font-size: 1.2rem;
    }
    .time{
      float: right;
      margin-right: -20px;
      font-style: italic;
    }

    .label{
      font-weight: bold;
      text-align: right;
    }

    .price{
      font-size: 1.5rem;
      font-style: italic;
      text-align: right;
    }

    @media screen and (max-width: 576px) {
      .label, #previous-events span, .date, .time  {
        text-align: center;
        width: 100%;
        display: block;
        float: none;
      }

      .date{
        font-size: 2rem;
      }

      [class*="col-"] {
        padding: 0px;
      }
      .row{
        margin-bottom: 15px;
      }   
    }

  </style>
{% endblock %}

{% block main %}
<div id="add-new-event" class="container">

    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-sm-5">Óraállás</div>
        <div class="col-sm-7"><input required type="number" name="km" id="id_km"></div>
      </div>
      <div class="row">
        <div class="col-sm-5">Üzemanyag</div>
        <div class="col-sm-7">
            <select name="petrol_type" id="id_petrol_type">
              {% for type in petrol_types %}
                <option value="{{ type.0 }}">{{ type.1 }}</option>
              {% endfor %}
            </select>
        </div>
      </div>
  
      <div class="row">
        <div class="col-sm-5">Benzinkút</div>
        <div class="col-sm-7">
            <select name="petrol_station" id="id_petrol_station">
              {% for station in petrol_stations %}
                <option value="{{ station.0 }}">{{ station.1 }}</option>
              {% endfor %}
            </select>
        </div>
      </div>
  
      <div class="row">
        <div class="col-sm-5">Mennyiség (l)</div>
        <div class="col-sm-7">
          <input required type="number" name="petrol_quantity_liter" id="id_petrol_quantity_liter">
        </div>
      </div>
  
      <div class="row">
        <div class="col-sm-5">Fizetett összeg (Ft)</div>
        <div class="col-sm-7">
          <input required type="number" name="price_ft" id="id_price_ft">
        </div>
      </div>
  
      <div class="row">
        <div class="col-6"></div>
        <div class="col-6">
          <input type="submit" value="MENTÉS">
        </div>
      </div>
  
    </form>
  </div>
{% endblock %}

{% block script %}
{% endblock %}

templates/tank/service.html
{% extends "tank/base.html" %}

{% block head %}
<style>

    .row{
      width: 100%;
    }

    input, select{
      width: 100%;
      height: 2.5rem;
    }

    textarea{
        width: 100%;
        height: 5rem;
        min-height: 2.5rem;
    }

    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }

    input[type=submit]{
      height: 70px;
      max-width: 200px;
      float: right;
      border: none;
      background-color: rgba(0, 128, 0, 0.2);
      transition: 1s;
      font-weight: bold;
    }

    input[type=submit]:hover{
      background-color: rgba(0, 128, 0, 0.4);
    }

    input[type=number] {
      -moz-appearance: textfield;
    }

    [class*="col-"] {
      padding: 10px;
    }

    .event{
      background-color: white;
      width: 100%;
      box-sizing: border-box;
      padding: 10px;
      border-radius: 5px;
      box-shadow:0px 0px 10px rgba(0, 0, 0, 0.5);
      margin-bottom: 50px;
    }

    .date{
      font-weight: bold;
      font-size: 1.2rem;
    }
    .time{
      float: right;
      margin-right: -20px;
      font-style: italic;
    }

    .label{
      font-weight: bold;
      text-align: right;
    }

    .price{
      font-size: 1.5rem;
      font-style: italic;
      text-align: right;
    }

    @media screen and (max-width: 576px) {
      .label, #previous-events span, .date, .time  {
        text-align: center;
        width: 100%;
        display: block;
        float: none;
      }

      .date{
        font-size: 2rem;
      }

      [class*="col-"] {
        padding: 0px;
      }
      .row{
        margin-bottom: 15px;
      }   
    }

  </style>
{% endblock %}

{% block main %}
<div id="add-new-event" class="container">

    <form action="{% url 'save_service' %}" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-sm-5">Óraállás</div>
        <div class="col-sm-7"><input required type="number" name="km" id="id_km"></div>
      </div>

      <div class="row">
        <div class="col-sm-5">Esemény</div>
        <div class="col-sm-7">
          <textarea required name="note" id="id_note" cols="30" rows="10"></textarea>
        </div>
      </div>
  
      <div class="row">
        <div class="col-sm-5">Fizetett összeg (Ft)</div>
        <div class="col-sm-7">
          <input required type="number" name="price_ft" id="id_price_ft">
        </div>
      </div>
  
      <div class="row">
        <div class="col-6"></div>
        <div class="col-6">
          <input type="submit" value="MENTÉS">
        </div>
      </div>
  
    </form>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/tank/stat.html
{% extends "tank/base.html" %}

{% block head %}
<style>
    .small{
        font-size: 0.8rem;
    }
    .row{
        margin-bottom: 20px;
    }

    @media screen and (max-width: 576px) {
        [class*="col-"] {
            text-align: center;
        }

        .row{
            border-top: 2px solid black;
            padding: 20px 0px;
        }

        .row:last-child{
            border-bottom: 2px solid black;
        }

        .data{
            font-size: 2rem;
        }
    }
</style>
{% endblock %}

{% block main %}
<div class="container stats">
    {% if last == None %}
        <h1>Legalább két tankolás szükséges, hogy minden statisztikai megjelenjen!</h1>
    {% else %}
    
    <div class="row">
        <div class="col-sm-6">Legutóbbi tankolás: </div>
        <div class="col-sm-6 data">{{ last.km }}km</div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            Fogyasztás 100km-en:<br>
            <span class="small">(Az utolsó két tankolás alapján)</span>
        </div>
        <div class="col-sm-6 data">
            {% if consumption == None %}
                -
            {% else %}
                {{ consumption }}l
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">Átlagosan tankolt mennyiség:</div>
        <div class="col-sm-6 data">{{ average_quantity }}l</div>
    </div>

    <div class="row">
        <div class="col-sm-6">Átlagosan fizetett összeg:</div>
        <div class="col-sm-6 data">{{ average_price }}Ft</div>
    </div>

    <div class="row">
        <div class="col-sm-6">Mérés óta elköltött pénz:</div>
        <div class="col-sm-6 data">{{ sum_price }}Ft</div>
    </div>

    {% endif %}
</div>
{% endblock %}

{% block script %}
{% endblock %}